# Generated by Django 2.2.7 on 2019-12-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_truck_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('truck_id', models.CharField(max_length=50)),
            ],
        ),
    ]
