# Generated by Django 2.2.7 on 2019-12-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_user_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_truck',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
